#!/usr/bin/env escript


main(Args) ->
    [Mode, PortStr] = Args,
    Port = list_to_integer(PortStr),

    case Mode of
      "passive" -> http_passive_server:start(Port);
      "active" -> http_active_server:start(Port)
    end,

    init:stop().
